# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Verify, Build and Deploy to test server

on:
  push:
    branches: [ "mainTesting" ]
  pull_request:
    branches: [ "mainTesting" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Check Chrome version
        run: chrome --version
      - name: Verify with Maven
        run: mvn -B package --file pom.xml test -X
        # run: mvn -B package --file pom.xml test
        #run: mvn -B clean package -Pproduction -X --file pom.xml
  
  build:
  
    runs-on: self-hosted
    needs: test
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml test
      - name: Take down Docker Compose
        run: docker compose -f /opt/webshop/docker-compose.yml down
      - name: Delete old war file
        run: rm /opt/webshop/data/test/*.war
      - name: Create test folder
        run: mkdir test && cp target/*.war test
      - name: Upload to Server
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: test
      - name: Copy runnable to docker folder
        run: cp test/*.war /opt/webshop/data/test/
      - name: Rename to webshop.war
        run: mv /opt/webshop/data/test/*.war /opt/webshop/data/test/webshop.war
      - name: Start Docker Compose
        run: docker compose -f /opt/webshop/docker-compose.yml up -d
