# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to production server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: Build with Maven
      run: mvn -B clean package -Pproduction --file pom.xml
    - name: Take down Docker Compose
      run: docker compose -f /opt/webshop/docker-compose.yml down
    - name: Delete old war file
      run: rm /opt/webshop/data/productive/*.war
    - name: Create production folder
      run: mkdir production && cp target/*.war production
    - name: Upload to Server  
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: production
    - name: Copy runnable to docker folder
      run: cp production/*.war /opt/webshop/data/productive/
    - name: Rename to webshop.war
      run: mv /opt/webshop/data/productive/*.war /opt/webshop/data/productive/webshop.war
    - name: Start Docker Compose
      run: docker compose -f /opt/webshop/docker-compose.yml up -d
